// RootLayout.js
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import { SideBar } from "@/components/SideBar";
import { cookies } from "next/headers";

const quantum = localFont({
  src: "./fonts/Quantumregular-MVmXr.otf",
  variable: "--font-quantum",
  weight: "100 900",
});

const outfit = localFont({
  src: "./fonts/Outfit-VariableFont_wght.ttf",
  variable: "--font-outfit",
  weight: "100 900"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
 

  return (
    <html lang="en" className={"font-[Outfit]"}>
      <body className="flex">
        <SideBar/>


          {children}
      </body>
    </html>
  );
}
