// RootLayout.js
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import { cookies } from "next/headers";

const quantum = localFont({
  src: "./fonts/Quantumregular-MVmXr.otf",
  variable: "--font-quantum",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar:state")?.value === "true";

  return (
    <html lang="en" className={quantum.variable}>
      <body>
        <SidebarProvider
          defaultOpen={defaultOpen}
          style={{
            "--sidebar-width": "10rem",
            "--sidebar-width-mobile": "10rem",
          }}
        >
          <AppSidebar variant="inset" />
          <SidebarInset>{children}</SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
